plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/mnt/m2/Código/opencode-ai-first"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]