import { ArchitectureAnalysis } from "../analysis/architectureDetector.js";

export interface EnrichedContext {
  project: {
    name: string;
    type: string;
    description: string;
  };
  architecture: {
    pattern: string;
    confidence: number;
    layers: Array<{
      name: string;
      components: string[];
      responsibility: string;
    }>;
  };
  techStack: {
    languages: string[];
    frameworks: string[];
    libraries: string[];
  };
  entryPoints: Array<{
    name: string;
    file: string;
    description: string;
  }>;
  flows: Array<{
    name: string;
    description: string;
    files: string[];
    dependencies: string[];
  }>;
  metrics: {
    totalFiles: number;
    totalSymbols: number;
    totalDependencies: number;
    averageComplexity: number;
  };
}

export class AIContextGenerator {
  generate(analysis: {
    architecture: ArchitectureAnalysis;
    symbols: Array<{
      id: string;
      name: string;
      type: string;
      file: string;
    }>;
    dependencies: {
      totalDependencies: number;
      dependencies: Array<{
        source: string;
        target: string;
        type: string;
      }>;
    };
    projectName: string;
  }): string {
    const enriched = this.enrichAnalysis(analysis);
    return this.renderMarkdown(enriched);
  }

  private enrichAnalysis(analysis: {
    architecture: ArchitectureAnalysis;
    symbols: Array<{
      id: string;
      name: string;
      type: string;
      file: string;
    }>;
    dependencies: {
      totalDependencies: number;
      dependencies: Array<{
        source: string;
        target: string;
        type: string;
      }>;
    };
    projectName: string;
  }): EnrichedContext {
    const uniqueFiles = [...new Set(analysis.symbols.map((s) => s.file))];
    const uniqueTypes = [...new Set(analysis.symbols.map((s) => s.type))];

    return {
      project: {
        name: analysis.projectName,
        type: this.detectProjectType(analysis),
        description: this.generateDescription(analysis),
      },
      architecture: {
        pattern: analysis.architecture.primary?.name || "Unknown",
        confidence: analysis.architecture.primary?.confidence || 0,
        layers: analysis.architecture.layers.map((layer) => ({
          name: layer.name,
          components: layer.symbols.slice(0, 10),
          responsibility: layer.responsibility,
        })),
      },
      techStack: {
        languages: this.extractLanguages(uniqueFiles),
        frameworks: this.detectFrameworks(analysis),
        libraries: this.detectLibraries(analysis),
      },
      entryPoints: analysis.architecture.entryPoints.slice(0, 5).map((ep) => ({
        name: ep.split("#")[1] || ep,
        file: ep.split("#")[0] || ep,
        description: this.describeEntryPoint(ep),
      })),
      flows: this.extractFlows(analysis),
      metrics: {
        totalFiles: uniqueFiles.length,
        totalSymbols: analysis.symbols.length,
        totalDependencies: analysis.dependencies.totalDependencies,
        averageComplexity: this.calculateComplexity(analysis),
      },
    };
  }

  private renderMarkdown(context: EnrichedContext): string {
    return `# AI Context: ${context.project.name}

## Project Overview

**Type**: ${context.project.type}  
**Description**: ${context.project.description}

## Architecture

### Pattern: ${context.architecture.pattern}
**Confidence**: ${(context.architecture.confidence * 100).toFixed(0)}%

### Layers

${context.architecture.layers
  .map(
    (layer) => `#### ${layer.name}
**Responsibility**: ${layer.responsibility}

**Key Components**:
${layer.components.map((c) => `- \`${c}\``).join("\n")}
`
  )
  .join("\n")}

## Tech Stack

### Languages
${context.techStack.languages.map((l) => `- ${l}`).join("\n")}

### Frameworks
${context.techStack.frameworks.map((f) => `- ${f}`).join("\n")}

### Key Libraries
${context.techStack.libraries.slice(0, 10).map((l) => `- ${l}`).join("\n")}

## Entry Points

${context.entryPoints
  .map(
    (ep) => `### ${ep.name}
- **File**: \`${ep.file}\`
- **Description**: ${ep.description}
`
  )
  .join("\n")}

## Business Flows

${context.flows
  .map(
    (flow) => `### ${flow.name}
${flow.description}

**Files involved**:
${flow.files.map((f) => `- \`${f}\``).join("\n")}

**Dependencies**:
${flow.dependencies.slice(0, 5).map((d) => `- ${d}`).join("\n")}
`
  )
  .join("\n")}

## Metrics

| Metric | Value |
|--------|-------|
| Total Files | ${context.metrics.totalFiles} |
| Total Symbols | ${context.metrics.totalSymbols} |
| Total Dependencies | ${context.metrics.totalDependencies} |
| Average Complexity | ${context.metrics.averageComplexity.toFixed(2)} |

## Getting Started for AI

1. **Read architecture.md** for detailed structure
2. **Check context/flows/** for business logic understanding
3. **See symbols.json** for complete API reference
4. **Review dependencies.json** for module relationships

---
*Generated by ai-first-cli v2.0 with semantic analysis*
`;
  }

  private detectProjectType(analysis: {
    symbols: Array<{ type: string; file: string }>;
    architecture: ArchitectureAnalysis;
  }): string {
    const hasComponents = analysis.symbols.some(
      (s) => s.type === "class" && s.file.includes("component")
    );
    const hasRoutes = analysis.symbols.some((s) => s.file.includes("route"));
    const hasModels = analysis.symbols.some((s) => s.file.includes("model") || s.file.includes("entity"));
    const hasServices = analysis.symbols.some((s) => s.file.includes("service"));
    
    const archPattern = analysis.architecture.primary?.name || "";
    const isAPIPattern = archPattern.includes("REST") || archPattern.includes("Layered") || archPattern.includes("API");
    const isMicroservice = archPattern.includes("Microservice");
    
    if (isMicroservice) return "Microservices Architecture";
    if (isAPIPattern && hasServices) return "REST API Service";
    if (isAPIPattern) return "REST API";
    if (hasComponents) return "Frontend Application";
    if (hasRoutes && hasModels) return "MVC Web Application";
    if (hasRoutes) return "API Application";
    if (archPattern) return archPattern.replace(/\s*\([^)]*\)/g, "").trim() + " Application";
    return "Backend Service";
  }

  private generateDescription(analysis: {
    architecture: ArchitectureAnalysis;
    symbols: Array<{ type: string }>;
  }): string {
    const patterns = analysis.architecture.primary
      ? [analysis.architecture.primary.name]
      : [];
    patterns.push(...analysis.architecture.secondary.map((s) => s.name));

    const entryPoints = analysis.architecture.entryPoints || [];
    
    if (entryPoints.length > 0) {
      const firstEp = entryPoints[0].split("#")[0] || entryPoints[0];
      const epName = firstEp.split("/").pop() || firstEp;
      
      const purposeParts: string[] = [];
      
      if (patterns.length > 0) {
        purposeParts.push(`**${patterns[0]}**`);
      }
      
      if (epName.toLowerCase().includes("auth") || epName.toLowerCase().includes("login")) {
        purposeParts.push("authentication system");
      } else if (epName.toLowerCase().includes("api") || epName.toLowerCase().includes("controller")) {
        purposeParts.push("API endpoints");
      } else if (epName.toLowerCase().includes("main") || epName.toLowerCase().includes("app")) {
        purposeParts.push("application");
      } else if (epName.toLowerCase().includes("cli") || epName.toLowerCase().includes("command")) {
        purposeParts.push("CLI tool");
      } else if (epName.toLowerCase().includes("worker") || epName.toLowerCase().includes("job")) {
        purposeParts.push("background worker");
      }
      
      if (purposeParts.length > 0) {
        return `This is a ${purposeParts.join(" ")}.`;
      }
    }
    
    if (patterns.length > 0) {
      return `This is a **${patterns.join(" / ")}** application.`;
    }
    
    return "This is a service-oriented application.";
  }

  private extractLanguages(files: string[]): string[] {
    const extensions = files.map((f) => f.split(".").pop() || "");
    const langMap: Record<string, string> = {
      ts: "TypeScript",
      tsx: "TypeScript (React)",
      js: "JavaScript",
      jsx: "JavaScript (React)",
      py: "Python",
      java: "Java",
      go: "Go",
      rs: "Rust",
      php: "PHP",
      rb: "Ruby",
    };

    return [...new Set(extensions.map((e) => langMap[e] || e).filter(Boolean))];
  }

  private detectFrameworks(analysis: {
    symbols: Array<{ name: string; file: string }>;
  }): string[] {
    const frameworks: string[] = [];
    const check = (pattern: string, name: string) => {
      if (
        analysis.symbols.some(
          (s) => s.name.includes(pattern) || s.file.includes(pattern.toLowerCase())
        )
      ) {
        frameworks.push(name);
      }
    };

    check("Controller", "NestJS / Express");
    check("Component", "React / Vue / Angular");
    check("Service", "Angular / NestJS");
    check("Model", "Django / Rails / Laravel");
    check("View", "Django / Rails");
    check("Route", "Express / Fastify");

    return [...new Set(frameworks)];
  }

  private detectLibraries(analysis: {
    dependencies: { dependencies: Array<{ target: string }> };
  }): string[] {
    const imports = analysis.dependencies.dependencies.map((d) => d.target);
    return [...new Set(imports)].slice(0, 20);
  }

  private describeEntryPoint(entryPoint: string): string {
    const name = entryPoint.split("#")[1] || entryPoint;
    const file = entryPoint.split("#")[0] || entryPoint;
    const lowerName = name.toLowerCase();
    const lowerFile = file.toLowerCase();

    if (lowerName.includes("main") || lowerName.includes("bootstrap")) return "Application entry point";
    if (lowerName.includes("server") || lowerName.includes("listen")) return "HTTP server bootstrap";
    if (lowerName.includes("app") && lowerName.includes("init")) return "Application initialization";
    if (lowerName.includes("index")) return "Module entry point / exports";
    if (lowerFile.includes("controller")) return "API endpoint handler";
    if (lowerFile.includes("route") || lowerFile.includes("router")) return "Route definition";
    if (lowerFile.includes("handler") || lowerFile.includes("action")) return "Request handler";
    if (lowerName.includes("cli") || lowerName.includes("command") || lowerName.includes("run")) return "CLI command";
    if (lowerName.includes("worker") || lowerName.includes("job") || lowerName.includes("task")) return "Background worker";
    if (lowerName.includes("consumer") || lowerName.includes("producer")) return "Message queue consumer/producer";
    if (lowerName.includes("scheduler") || lowerName.includes("cron")) return "Scheduled job";
    if (lowerName.includes("auth") || lowerName.includes("login") || lowerName.includes("signup")) return "Authentication handler";
    if (lowerFile.includes("middleware")) return "Request middleware";
    if (lowerFile.includes("service")) return "Business logic service";
    if (lowerFile.includes("model") || lowerFile.includes("entity")) return "Data model";
    if (lowerFile.includes("repository") || lowerFile.includes("dao")) return "Data access layer";
    return "Application entry point";
  }

  private extractFlows(analysis: {
    architecture: ArchitectureAnalysis;
    symbols: Array<{ id: string; name: string; file: string; type: string }>;
  }): EnrichedContext["flows"] {
    const flows: EnrichedContext["flows"] = [];

    const entryPoints = analysis.architecture.entryPoints;
    for (const ep of entryPoints.slice(0, 5)) {
      const epName = ep.split("#")[1] || ep;
      const epFile = ep.split("#")[0] || ep;

      const relatedFiles = analysis.symbols
        .filter((s) => s.file.includes(epName.toLowerCase().replace(/controller|handler/g, "")))
        .map((s) => s.file);

      flows.push({
        name: epName,
        description: `Business flow starting at ${epName}`,
        files: [...new Set([epFile, ...relatedFiles])].slice(0, 5),
        dependencies: [],
      });
    }

    return flows;
  }

  private calculateComplexity(analysis: {
    symbols: Array<{ type: string }>;
    dependencies: { dependencies: Array<unknown> };
  }): number {
    const symbolCount = analysis.symbols.length;
    const depCount = analysis.dependencies.dependencies.length;
    return symbolCount > 0 ? depCount / symbolCount : 0;
  }
}

export const aiContextGenerator = new AIContextGenerator();
