import { ArchitectureAnalysis } from "../analysis/architectureDetector.js";

export class ArchitectureGenerator {
  generate(
    analysis: ArchitectureAnalysis,
    dependencyGraph: {
      nodes: string[];
      edges: Array<{ from: string; to: string; type: string }>;
    }
  ): string {
    return `# Architecture

## Pattern: ${analysis.primary?.name || "Unknown"}

**Confidence**: ${((analysis.primary?.confidence || 0) * 100).toFixed(0)}%

### Evidence
${analysis.primary?.evidence.map((e) => `- ${e}`).join("\n") || "- No strong pattern detected"}

${analysis.secondary.length > 0 ? `
### Secondary Patterns
${analysis.secondary.map((p) => `- **${p.name}** (${(p.confidence * 100).toFixed(0)}%)`).join("\n")}
` : ""}

## Architecture Diagram

\`\`\`
${this.generateAsciiDiagram(analysis)}
\`\`\`

## Layer Overview

| Layer | Components | Responsibility |
|-------|------------|----------------|
${analysis.layers.map((layer) => `| ${layer.name} | ${layer.symbols.length} | ${layer.responsibility} |`).join("\n")}

## Mermaid Diagram

\`\`\`mermaid
${this.generateMermaidDiagram(analysis, dependencyGraph)}
\`\`\`

## Entry Points

${analysis.entryPoints.slice(0, 10).map((ep) => `- \`${ep}\``).join("\n")}

## Module Dependencies

\`\`\`mermaid
graph TD
${this.generateDependencyGraph(dependencyGraph)}
\`\`\`

## Recommendations

${this.generateRecommendations(analysis)}

---
*Generated by ai-first-cli v2.0*
`;
  }

  private generateAsciiDiagram(analysis: ArchitectureAnalysis): string {
    const layers = analysis.layers;
    if (layers.length === 0) return "No layers detected";

    let diagram = "";
    const maxWidth = 50;

    for (let i = 0; i < layers.length; i++) {
      const layer = layers[i];
      const title = ` ${layer.name} `;
      const padding = Math.max(0, (maxWidth - title.length) / 2);
      const leftPad = "─".repeat(Math.floor(padding));
      const rightPad = "─".repeat(Math.ceil(padding));

      diagram += `┌${leftPad}${title}${rightPad}┐\n`;

      const components = layer.symbols.slice(0, 3);
      for (const component of components) {
        const name = component.split("#")[1] || component;
        const line = `│  • ${name.padEnd(maxWidth - 4)}│`;
        diagram += `${line}\n`;
      }

      if (layer.symbols.length > 3) {
        diagram += `│  ... and ${layer.symbols.length - 3} more${"".padEnd(maxWidth - 15)}│\n`;
      }

      diagram += `└${"─".repeat(maxWidth)}┘\n`;

      if (i < layers.length - 1) {
        diagram += `${" ".repeat(maxWidth / 2)}↓\n`;
      }
    }

    return diagram;
  }

  private generateMermaidDiagram(
    analysis: ArchitectureAnalysis,
    dependencyGraph: {
      nodes: string[];
      edges: Array<{ from: string; to: string; type: string }>;
    }
  ): string {
    const lines: string[] = [];
    lines.push("graph TD");

    const subgraphs = new Map<string, string[]>();

    for (const layer of analysis.layers) {
      const nodeIds: string[] = [];
      for (const symbol of layer.symbols.slice(0, 5)) {
        const id = symbol.replace(/[^a-zA-Z0-9]/g, "_");
        const name = symbol.split("#")[1] || symbol;
        nodeIds.push(id);
        lines.push(`    ${id}[${name}]`);
      }
      subgraphs.set(layer.name, nodeIds);
    }

    for (const [layerName, nodeIds] of subgraphs) {
      if (nodeIds.length > 0) {
        lines.push(`    subgraph ${layerName}`);
        for (const id of nodeIds) {
          lines.push(`        ${id}`);
        }
        lines.push(`    end`);
      }
    }

    const addedEdges = new Set<string>();
    for (const edge of dependencyGraph.edges.slice(0, 10)) {
      const from = edge.from.replace(/[^a-zA-Z0-9]/g, "_");
      const to = edge.to.replace(/[^a-zA-Z0-9]/g, "_");
      const edgeKey = `${from}-->${to}`;
      if (!addedEdges.has(edgeKey)) {
        lines.push(`    ${from}-->${to}`);
        addedEdges.add(edgeKey);
      }
    }

    return lines.join("\n");
  }

  private generateDependencyGraph(dependencyGraph: {
    nodes: string[];
    edges: Array<{ from: string; to: string; type: string }>;
  }): string {
    const lines: string[] = [];
    const added = new Set<string>();

    for (const edge of dependencyGraph.edges.slice(0, 15)) {
      const from = edge.from.replace(/[^a-zA-Z0-9]/g, "_");
      const to = edge.to.replace(/[^a-zA-Z0-9]/g, "_");
      const key = `${from}-->${to}`;

      if (!added.has(key)) {
        const label = edge.type === "import" ? "" : `|${edge.type}|`;
        lines.push(`    ${from}[${edge.from}] -->${label} ${to}[${edge.to}]`);
        added.add(key);
      }
    }

    return lines.join("\n");
  }

  private generateRecommendations(analysis: ArchitectureAnalysis): string {
    const recommendations: string[] = [];
    
    const pattern = analysis.primary?.name || "";
    const isAPI = pattern.includes("REST API") || pattern.includes("Layered Architecture");
    const isCLI = pattern.includes("CLI");
    const isMicroservice = pattern.includes("Microservices");
    
    if (!analysis.primary) {
      recommendations.push("- Consider adopting a well-defined architectural pattern");
    }
    
    if (isCLI) {
      recommendations.push("- CLI tools benefit from clear command structure and error handling");
      recommendations.push("- Consider using a command parser library (clap, argparse, etc.)");
    } else if (isAPI) {
      if (analysis.layers.length === 0) {
        recommendations.push("- No clear layer separation detected. Consider organizing code into layers (API → Service → Data)");
      } else if (analysis.layers.length < 3) {
        recommendations.push("- Consider adding more separation of concerns (API, Service, Data layers)");
      }
    } else if (!isMicroservice) {
      if (analysis.layers.length === 0) {
        recommendations.push("- No clear layer separation detected. Consider organizing code into layers");
      } else if (analysis.layers.length < 3) {
        recommendations.push("- Consider adding more separation of concerns (currently only " + analysis.layers.length + " layers)");
      }
    }
    
    if (analysis.entryPoints.length === 0) {
      recommendations.push("- No clear entry points found. Define main functions or controllers");
    } else if (analysis.entryPoints.length > 10) {
      recommendations.push("- Many entry points detected. Consider consolidating");
    }
    
    if (analysis.secondary.length > 2) {
      recommendations.push("- Multiple patterns detected. Consider simplifying architecture");
    }
    
    if (recommendations.length === 0) {
      return "- Architecture looks well-structured. Keep the consistency as the project grows.";
    }
    
    return recommendations.join("\n");
  }
}

export const architectureGenerator = new ArchitectureGenerator();
