import { FileInfo } from "../core/repoScanner.js";
import { readJsonFile } from "../utils/fileUtils.js";
import path from "path";

export interface Entrypoint {
  name: string;
  path: string;
  type: "cli" | "api" | "worker" | "server" | "client" | "library" | "config" | "test" | "build" | "lint" | "formatter" | "other";
  description: string;
  command?: string;
}

export function discoverEntrypoints(files: FileInfo[], rootDir: string): Entrypoint[] {
  const entrypoints: Entrypoint[] = [];
  
  try {
    const pkgPath = path.join(rootDir, "package.json");
    const pkg = readJsonFile(pkgPath) as { 
      main?: string; 
      bin?: string | Record<string, string>; 
      module?: string; 
      types?: string; 
      typings?: string; 
      scripts?: Record<string, string> 
    };
    
    if (pkg.main) {
      entrypoints.push({ name: "Main", path: pkg.main, type: "library", description: "Main entry point" });
    }
    
    if (pkg.bin) {
      const bins = typeof pkg.bin === 'string' ? { main: pkg.bin } : pkg.bin;
      for (const [name, binPath] of Object.entries(bins)) {
        entrypoints.push({
          name: name === 'main' ? 'CLI' : name,
          path: String(binPath),
          type: "cli",
          description: `CLI: ${name}`,
          command: name === 'main' ? 'npx pkg' : `npx ${name}`,
        });
      }
    }
    
    if (pkg.types || pkg.typings) {
      entrypoints.push({ name: "Types", path: String(pkg.types || pkg.typings), type: "library", description: "TypeScript definitions" });
    }
    
    if (pkg.scripts) {
      for (const [scriptName, scriptCmd] of Object.entries(pkg.scripts)) {
        const type = getScriptType(scriptName);
        if (type) {
          entrypoints.push({ name: scriptName, path: `package.json#scripts.${scriptName}`, type, description: `${scriptName}: ${scriptCmd}`, command: `npm run ${scriptName}` });
        }
      }
    }
  } catch {}
  
  // From file names
  const patterns: Record<string, { type: Entrypoint["type"]; desc: string }> = {
    "index.ts": { type: "library", desc: "Entry point" }, "main.ts": { type: "server", desc: "Main" },
    "server.ts": { type: "server", desc: "Server" }, "api.ts": { type: "api", desc: "API" },
    "cli.ts": { type: "cli", desc: "CLI" }, "worker.ts": { type: "worker", desc: "Worker" },
  };
  
  for (const file of files) {
    const p = patterns[file.name];
    if (p && !entrypoints.some(e => e.path === file.relativePath)) {
      entrypoints.push({ name: file.name, path: file.relativePath, type: p.type, description: p.desc });
    }
  }
  
  return entrypoints;
}

function getScriptType(name: string): Entrypoint["type"] | null {
  const l = name.toLowerCase();
  if (l.includes("start") || l.includes("dev") || l.includes("serve")) return "server";
  if (l.includes("build") || l.includes("compile")) return "build";
  if (l.includes("test")) return "test";
  if (l.includes("lint")) return "lint";
  if (l.includes("format")) return "formatter";
  return null;
}

export function generateEntrypointsFile(entrypoints: Entrypoint[]): string {
  const grouped = new Map<string, Entrypoint[]>();
  for (const ep of entrypoints) {
    if (!grouped.has(ep.type)) grouped.set(ep.type, []);
    grouped.get(ep.type)?.push(ep);
  }
  
  let content = "# Entrypoints\n\n";
  const labels: Record<string, string> = { cli: "CLI", api: "API", worker: "Workers", server: "Server", client: "Client", library: "Library", test: "Tests", build: "Build", lint: "Lint", formatter: "Formatter", other: "Other" };
  
  for (const [type, eps] of grouped) {
    content += `## ${labels[type] || type}\n\n| Name | Path | Command |\n|------|------|--------|\n`;
    for (const ep of eps) content += `| ${ep.name} | \`${ep.path}\` | ${ep.command || "-"} |\n`;
    content += "\n";
  }
  
  return content + "---\n*Generated by ai-first*\n";
}
