import path from "path";
import type { ArchitectureAnalysis } from "../analyzers/architecture.js";
import type { TechStack } from "../analyzers/techStack.js";
import type { ProjectSetup } from "../utils/projectSetupExtractor.js";
import type { FreshnessResult } from "./contextManifest.js";

export interface AgentBriefParams {
  rootDir: string;
  setup: ProjectSetup;
  techStack: TechStack;
  architecture: ArchitectureAnalysis;
  freshness?: FreshnessResult;
}

export function generateAgentBrief(params: AgentBriefParams): string {
  const lines: string[] = [];
  const commands = [
    ["Install", params.setup.installCommand],
    ["Build", params.setup.buildCommand],
    ["Test", params.setup.testCommand],
    ["Dev", params.setup.devCommand],
    ["Start", params.setup.startCommand],
  ].filter(([, command]) => Boolean(command));

  lines.push("# Agent Brief");
  lines.push("");
  lines.push("## Project");
  lines.push(`- Root: \`${params.rootDir}\``);
  lines.push(`- Pattern: ${params.architecture.pattern}`);
  lines.push(`- Languages: ${params.techStack.languages.join(", ") || "Unknown"}`);
  lines.push(`- Frameworks: ${params.techStack.frameworks.join(", ") || "None detected"}`);
  lines.push(`- Testing: ${params.techStack.testing.join(", ") || params.setup.testCommand || "Unknown"}`);
  lines.push("");

  if (commands.length > 0) {
    lines.push("## Commands");
    for (const [label, command] of commands) {
      lines.push(`- ${label}: \`${command}\``);
    }
    lines.push("");
  }

  const keyModules = params.architecture.modules
    .filter(module => ["src/commands", "src/core", "src/analyzers", "src/utils", "src/mcp", "tests", "docs"].includes(module.path))
    .slice(0, 8);

  if (keyModules.length > 0) {
    lines.push("## Where To Work");
    for (const module of keyModules) {
      lines.push(`- \`${module.path}\`: ${module.responsibility}`);
    }
    lines.push("");
  }

  lines.push("## Contracts");
  lines.push("- Keep source changes in `src/`; generated `dist/` files are build outputs.");
  lines.push("- CLI commands own argument parsing, user output and exit codes.");
  lines.push("- Reusable behavior should live in core services so CLI and MCP can share it.");
  lines.push("- ESM imports in TypeScript source should use `.js` runtime extensions.");
  lines.push("- Generated context lives in `ai-context/`; verify freshness before relying on it.");
  lines.push("");

  const envVars = params.setup.envVars.filter(envVar => envVar.required);
  if (envVars.length > 0) {
    lines.push("## Required Environment");
    for (const envVar of envVars) {
      lines.push(`- \`${envVar.name}\``);
    }
    lines.push("");
  }

  lines.push("## Context Freshness");
  if (params.freshness) {
    lines.push(`- Status: ${params.freshness.fresh ? "fresh" : "stale"}`);
    lines.push(`- Reason: ${params.freshness.reason}`);
    if (params.freshness.generatedAt) lines.push(`- Generated: ${params.freshness.generatedAt}`);
  } else {
    lines.push("- Run `af doctor context` before relying on generated context.");
  }
  lines.push("");

  lines.push("## Before Editing");
  lines.push("- Run `npm run build` after TypeScript changes.");
  lines.push("- Run targeted Vitest tests for changed analyzers or commands.");
  lines.push("- Run `af verify ai-context` when generated context is part of the workflow.");
  lines.push("");
  lines.push("---");
  lines.push(`Generated by ai-first for \`${path.basename(params.rootDir)}\`.`);

  return lines.join("\n");
}
